### busca todos

GET http://localhost:3000/api/evento

### busca uno
GET http://localhost:3000/api/evento/6566145214a1a83b57231c01


### añade 
POST http://localhost:3000/api/evento
Content-Type: application/json

{
  "description": "Navidad",
  "fechaHoraIni": "2023-12-24T20:00:00.000Z",
  "fechaHoraFin": "2023-12-25T06:00:00.000Z"
}


### modifica PUT

PUT http://localhost:3000/api/evento/656614c314a1a83b57231c09
Content-Type: application/json

{
  "description": "Fiesta Año Nuevo",
  "fechaHoraIni": "2023-12-31T21:00:00.000Z",
  "fechaHoraFin": "2024-01-01T07:00:00.000Z"
}


### modifica PATCH

PATCH http://localhost:3000/api/evento/656614c314a1a83b57231c09
Content-Type: application/json

{
  "description": "La Gran Fiesta de Año Nuevo"
}


### ELIMINA
DELETE  http://localhost:3000/api/evento/656a4cbeefd3b1c20e4fb0cf