### obterner todas los tipos de competicion
GET http://localhost:3000/api/competition-type

### obtener un tipo de competicion por su id

GET http://localhost:3000/api/competition-type/6524b0b2a1b2ef79b1d2bb07

###añado un tipo de competencia nuevo
POST http://localhost:3000/api/competition-type
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTI4ODVlYzA1YmVhYTI4ZmU3NGUwYmIiLCJpYXQiOjE2OTcyNDExODQsImV4cCI6MTY5NzI0ODM4NH0.f-fI0LaelawbiLSsbHJwuh7XAZPCbOi0MzjD1kE_8vg
Content-Type: application/json

#se puede ver que no afecta 
{
  "description": "Levantamiento de dedo anular",
  "rules": "No se puede levantar un dedo que no sea el anular, si lo hace, quedará descalificado. Gana el que levante mas veces el dedo anular"
}

### modifico totalmente un tipo de competencia
PUT http://localhost:3000/api/competition-type/6529db6ef2fe0cd8b251fa3b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTI4ODVlYzA1YmVhYTI4ZmU3NGUwYmIiLCJpYXQiOjE2OTcyNDExODQsImV4cCI6MTY5NzI0ODM4NH0.f-fI0LaelawbiLSsbHJwuh7XAZPCbOi0MzjD1kE_8vg
Content-Type: application/json

{
  "id": "lmm",
  "description": "Levantamiento de dedo meñique",
  "rules": "No se puede levantar un dedo que no sea el meñique, si lo hace, quedará descalificado. Gana el que levante más veces el dedo meñique"
}


### modifico parcialmente un tipo de competencia
PATCH  http://localhost:3000/api/competition-type/6529db6ef2fe0cd8b251fa3b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTI4ODVlYzA1YmVhYTI4ZmU3NGUwYmIiLCJpYXQiOjE2OTcyNDExODQsImV4cCI6MTY5NzI0ODM4NH0.f-fI0LaelawbiLSsbHJwuh7XAZPCbOi0MzjD1kE_8vg
Content-Type: application/json

{
  "id": "lmmq"
}

### elimino una persona
DELETE http://localhost:3000/api/competition-type/6529db6ef2fe0cd8b251fa3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTI4ODVlYzA1YmVhYTI4ZmU3NGUwYmIiLCJpYXQiOjE2OTcyNDExODQsImV4cCI6MTY5NzI0ODM4NH0.f-fI0LaelawbiLSsbHJwuh7XAZPCbOi0MzjD1kE_8vg
