### obterner todas las personas
GET http://localhost:3000/api/person?page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1Mjg4NWVjMDViZWFhMjhmZTc0ZTBiYiIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiU0EiLCJ1cGRhdGVkQXQiOiIyMDIzLTEyLTE0VDEzOjQ2OjAwLjg3MloifSwiaWF0IjoxNzA1NjkxNjQ1LCJleHAiOjE3MDU2OTg4NDV9.UMdN7lAdl7WKt9m3GJmt-KXkUlDbKEa678A-HidCkL8

### 
GET http://localhost:3000/api/person/65258a4829f08db9498afe2d

###añado una persona nueva
POST http://localhost:3000/api/person
Content-Type: application/json

{
  "dni": "44857721",
  "firstName": "Matias",
  "lastName": "Bernardi",
  "phone": "3329577636",
  "email": "matias.bernardi.1@gmail1.com",
  "birthdate": "2003-04-23T18:25:43.510Z",
}

### modifico totalmente una persona
PUT http://localhost:3000/api/person/65288573d0649bcd9624844
Content-Type: application/json

{
  "dni": "44857727",
  "firstName": "Juan",
  "lastName": "Perez",
  "phone": "000-000-000",
  "email": "perazajuana@hotmail.coms",
  "birthdate": "1981-01-01T00:00:00.000Z"
}


### modifico parcialmente una persona
PATCH  http://localhost:3000/api/person/65288573d0649bcd96248440
Content-Type: application/json

{
  "dni": "12345677",
  "firstName": "Ernesto",
  "birthdate": "1981-01-01T00:00:00.000Z"
}

### elimino una persona
DELETE http://localhost:3000/api/person/659568cecaaab3336b981b82
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1OTU2OGNlY2FhYWIzMzM2Yjk4MWI4MiIsImRuaSI6IjQ0ODU3NzIxIiwiZmlyc3ROYW1lIjoiTWF0aWFzIiwibGFzdE5hbWUiOiJCZXJuYXJkaSIsInBob25lIjoiMzMyOTU3NzYzNiIsImVtYWlsIjoibWF0aWFzLmJlcm5hcmRpLjFAZ21haWwxLmNvbSIsImJpcnRoZGF0ZSI6IjIwMDMtMDQtMjNUMTg6MjU6NDMuNTEwWiIsInBhc3N3b3JkIjoiJDJhJDEwJFF2YjY4MklWSmlCb3poUU9Cc3hvVE9WWVlwM3M3RGZkTEl0cWl5U2Y0eUFOd1d1U2FJMGZHIiwiY3JlYXRlZEF0IjoiMjAyNC0wMS0wM1QxNDowMTo1MS4wMTdaIiwidXBkYXRlZEF0IjoiMjAyNC0wMS0wM1QxNDowMTo1MS4wMTdaIn0sImlhdCI6MTcwNDI5MDUxNiwiZXhwIjoxNzA0Mjk3NzE2fQ.EOb2pbTMXk0XrR5n4wK-7Q0mRRtUy9VRDCa9flILe60

//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1NGMwMDE5NDgxODMxMzc0Y2Q2Y2RlMyIsImRuaSI6IjQ0ODU3NzI3IiwiZmlyc3ROYW1lIjoiTWF0aWFzIiwibGFzdE5hbWUiOiJCZXJuYXJkaSIsInBob25lIjoiMTIzNDU2NyIsImVtYWlsIjoibWF0aWFzLmJlcm5hcmRpLjFAZ21haWwuY29tIiwiYmlydGhkYXRlIjoiMjAwMy0wNC0yM1QwMzowMDowMC4wMDBaIiwicGFzc3dvcmQiOiIkMmEkMTAkSVNXTzhmQkJsR0JQSTNJZkJJejNsZW1YQWguejYuOEh1TWg3bUE3cHV3bzVzYXNYTTY4VVciLCJjcmVhdGVkQXQiOiIyMDIzLTExLTA4VDIxOjM5OjM3LjYxNVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEyLTEzVDIwOjAzOjQ2LjI2N1oifSwiaWF0IjoxNzAzMjkyNDE2LCJleHAiOjE3MDMyOTk2MTZ9.SfATYlgsf3xWDenWOOtNx7T68a_-BSE9-mawTRcKB7w