### obterner todas las personas
GET http://localhost:3000/api/person

### obtener una persona por su id

GET http://localhost:3000/api/person/6ba7b810-9dad-11d1-80b4-00c04fd430c8

###añado una persona nueva
POST http://localhost:3000/api/person
Content-Type: application/json

{
  "dni": "44857727",
  "firstName": "Matias",
  "lastName": "Bernardi",
  "phone": "3329577636",
  "email": "matias.bernardi.1@gmail.com",
  "birthdate": "2003-04-23T18:25:43.511Z"
}

### modifico totalmente una persona
PUT http://localhost:3000/api/person/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
  "dni": "12345677",
  "firstName": "Juana",
  "lastName": "Pereza",
  "phone": "000-000-000",
  "email": "perazajuana@hotmail.com",
  "birthdate": "1981-01-01T00:00:00.000Z"
}


### modifico parcialmente una persona
PATCH  http://localhost:3000/api/person/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
  "dni": "12345677",
  "firstName": "Ernesto",
  "birthdate": "1981-01-01T00:00:00.000Z"
}

### elimino una persona
DELETE http://localhost:3000/api/person/550e8400-e29b-41d4-a716-446655440000
