
### LOGIN
POST http://localhost:3000/api/auth/admin/login
Content-Type: application/json

{
  "username": "admin",
}

### LOGIN Personas
POST http://localhost:3000/api/auth/user/login
Content-Type: application/json

{
  "username": "matias.bernardi.1@gmail.com",
}
