GET http://localhost:3000/api/competitor?page=1&person=654c0019481831374cd6cde3&evento=65a31e33b59034a48cd363a1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1NGMwMDE5NDgxODMxMzc0Y2Q2Y2RlMyIsImRuaSI6IjQ0ODU3NzI3IiwiZmlyc3ROYW1lIjoiTWF0aWFzIiwibGFzdE5hbWUiOiJCZXJuYXJkaSIsInBob25lIjoiMTIzNDU2NyIsImVtYWlsIjoibWF0aWFzLmJlcm5hcmRpLjFAZ21haWwuY29tIiwiYmlydGhkYXRlIjoiMjAwMy0wNC0yM1QwMzowMDowMC4wMDBaIiwicGFzc3dvcmQiOiIkMmEkMTAkSWtmc3g2TG5XbDguSnVuRFNQRFgxT0tMUkp2emRZN2xmajhnNkIzU21jU1NzLjhyZGU3ZnkiLCJjcmVhdGVkQXQiOiIyMDIzLTExLTA4VDIxOjM5OjM3LjYxNVoiLCJ1cGRhdGVkQXQiOiIyMDI0LTAyLTI5VDE0OjE2OjA5LjcxNloifSwiaWF0IjoxNzA5MjE4NTkwLCJleHAiOjE3MDkyMjU3OTB9.qK5m-YSBI0BKUuZr3l-f_tCosO20AGIplJaISoY1l-M

###

POST http://localhost:3000/api/competitor
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1Mjg4NWVjMDViZWFhMjhmZTc0ZTBiYiIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiU0EiLCJ1cGRhdGVkQXQiOiIyMDIzLTEyLTE0VDEzOjQ2OjAwLjg3MloifSwiaWF0IjoxNzA1NjkxNjQ1LCJleHAiOjE3MDU2OTg4NDV9.UMdN7lAdl7WKt9m3GJmt-KXkUlDbKEa678A-HidCkL8
Content-Type: application/json

{
  "person": "65a1685225c29ba47030dcc3",
  "competition": "65a67e6a293fd7648d2abb5c"
}

###

PUT http://localhost:3000/api/competitor/65a9397fcea7791b53c4a4b2
Content-Type: application/json

{
  "person": "654c0019481831374cd6cde3",
  "competition": "65a68132293fd7648d2abbc0"
}


###

DELETE http://localhost:3000/api/competitor/65a9390d417d20358fdfc6f1
