GET http://localhost:3000/api/competitor?page=1&person=654c0019481831374cd6cde3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1NGMwMDE5NDgxODMxMzc0Y2Q2Y2RlMyIsImRuaSI6IjQ0ODU3NzI3IiwiZmlyc3ROYW1lIjoiTWF0aWFzIiwibGFzdE5hbWUiOiJCZXJuYXJkaSIsInBob25lIjoiMTIzNDU2NyIsImVtYWlsIjoibWF0aWFzLmJlcm5hcmRpLjFAZ21haWwuY29tIiwiYmlydGhkYXRlIjoiMjAwMy0wNC0yM1QwMzowMDowMC4wMDBaIiwicGFzc3dvcmQiOiIkMmEkMTAkSVNXTzhmQkJsR0JQSTNJZkJJejNsZW1YQWguejYuOEh1TWg3bUE3cHV3bzVzYXNYTTY4VVciLCJjcmVhdGVkQXQiOiIyMDIzLTExLTA4VDIxOjM5OjM3LjYxNVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTEyLTEzVDIwOjAzOjQ2LjI2N1oifSwiaWF0IjoxNzA2MDQ3Nzk3LCJleHAiOjE3MDYwNTQ5OTd9.mkghgHpQNvVvW5C4-DYc9z79WVq-OCxO60itr0aWyJs
###

POST http://localhost:3000/api/competitor
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1Mjg4NWVjMDViZWFhMjhmZTc0ZTBiYiIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiU0EiLCJ1cGRhdGVkQXQiOiIyMDIzLTEyLTE0VDEzOjQ2OjAwLjg3MloifSwiaWF0IjoxNzA1NjkxNjQ1LCJleHAiOjE3MDU2OTg4NDV9.UMdN7lAdl7WKt9m3GJmt-KXkUlDbKEa678A-HidCkL8
Content-Type: application/json

{
  "person": "65a1685225c29ba47030dcc3",
  "competition": "65a67e6a293fd7648d2abb5c"
}

###

PUT http://localhost:3000/api/competitor/65a9397fcea7791b53c4a4b2
Content-Type: application/json

{
  "person": "654c0019481831374cd6cde3",
  "competition": "65a68132293fd7648d2abbc0"
}


###

DELETE http://localhost:3000/api/competitor/65a9390d417d20358fdfc6f1
